package clock;

import clock.abstractGui.AbstractClockFrame;
import clock.analog.AnalogClock;
import clock.binary.BinaryClock;
import clock.digital.DigitalClock;
import clock.timer.ClockTimer;
import clock.util.GridLayoutStrategy;
import clock.util.SimpleLayoutStrategy;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @todo implémenter différent layout. Regrde dans la package util
 * @todo possible de créer d'autre montre regardeé ce qui à déjà été fait pour analog et digital clock dans cette classe
 * @author leo
 */
public class ClockLauncher extends javax.swing.JFrame {

    private ClockTimer timer;
    private ArrayList<JFrame> clocks = new ArrayList<>();

    /**
     * Creates new form ClockLauncher
     */
    public ClockLauncher() {
        initComponents();
        setTitle("Clock launcher");
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        this.timer = new ClockTimer();
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDigital = new javax.swing.JButton();
        jButtonAnalog = new javax.swing.JButton();
        jButtonBinary = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCloseAll = new javax.swing.JMenuItem();
        jMenuQuit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuGridLayout = new javax.swing.JMenuItem();
        jMenuLineLayout = new javax.swing.JMenuItem();
        jMenuSimple = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonDigital.setText("Digital clock");
        jButtonDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDigitalActionPerformed(evt);
            }
        });

        jButtonAnalog.setText("Analog clock");
        jButtonAnalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalogActionPerformed(evt);
            }
        });

        jButtonBinary.setText("Binary clock");
        jButtonBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBinaryActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuCloseAll.setText("Close all");
        jMenuCloseAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCloseAllActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCloseAll);

        jMenuQuit.setText("Quit...");
        jMenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuQuit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Layout");

        jMenuGridLayout.setText("Grid layout");
        jMenuGridLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGridLayoutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuGridLayout);

        jMenuLineLayout.setText("Line layout");
        jMenuLineLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLineLayoutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuLineLayout);

        jMenuSimple.setText("simple layout");
        jMenuSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSimpleActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSimple);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jButtonBinary, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButtonDigital, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButtonAnalog, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonDigital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonAnalog, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonBinary, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalogActionPerformed
        clocks.add(new AnalogClock(timer));
    }//GEN-LAST:event_jButtonAnalogActionPerformed

    private void jMenuCloseAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCloseAllActionPerformed
        for (JFrame clock : clocks) {
            clock.dispose();
        }
    }//GEN-LAST:event_jMenuCloseAllActionPerformed

    private void jMenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuQuitActionPerformed

    private void jMenuLineLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLineLayoutActionPerformed
        // TODO implémenter et créer le layout
    }//GEN-LAST:event_jMenuLineLayoutActionPerformed

    private void jMenuGridLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGridLayoutActionPerformed
        GridLayoutStrategy gridLayoutStrategy  = new GridLayoutStrategy();
        gridLayoutStrategy.doLayout(clocks);
    }//GEN-LAST:event_jMenuGridLayoutActionPerformed

    private void jButtonDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDigitalActionPerformed
        clocks.add(new DigitalClock(timer));
    }//GEN-LAST:event_jButtonDigitalActionPerformed

    private void jMenuSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSimpleActionPerformed
        SimpleLayoutStrategy layoutStrategy = new SimpleLayoutStrategy();
        layoutStrategy.doLayout(clocks);
    }//GEN-LAST:event_jMenuSimpleActionPerformed

    private void jButtonBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBinaryActionPerformed
        clocks.add(new BinaryClock(timer));
    }//GEN-LAST:event_jButtonBinaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClockLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClockLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClockLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClockLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClockLauncher().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnalog;
    private javax.swing.JButton jButtonBinary;
    private javax.swing.JButton jButtonDigital;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCloseAll;
    private javax.swing.JMenuItem jMenuGridLayout;
    private javax.swing.JMenuItem jMenuLineLayout;
    private javax.swing.JMenuItem jMenuQuit;
    private javax.swing.JMenuItem jMenuSimple;
    // End of variables declaration//GEN-END:variables
}
