/*
 * ChangeDialog.java
 *
 * Created on 4. octobre 2001, 15:32
 */

package shapes.gui;

import shapes.WorkShapes;

/**
 *
 * @author  fuhrer
 */
public class ChangeDialog extends javax.swing.JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3257006557739758384L;
	private WorkShapes w;
    
    /** Creates new form ChangeDialog */
    public ChangeDialog(java.awt.Frame parent) {
        super(parent, true);
        w = (WorkShapes)parent;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        setTitle("Change Shape");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter the ID of the shape to change: ");
        getContentPane().add(jLabel1);

        id.setColumns(3);
        getContentPane().add(id);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        dispose();
        w.changeShape(Integer.valueOf(id.getText()).intValue());
    }//GEN-LAST:event_jButton1ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
