/*
 * ClearOneDialog.java
 *
 * Created on 15. novembre 2001, 10:07
 */

package shapes.gui;

import shapes.WorkShapes;

/**
 *
 * @author  fuhrer
 */
public class ClearOneDialog extends javax.swing.JDialog {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 3258417248254310200L;
	private WorkShapes w;
    
    /** Creates new form ClearOneDialog */
    public ClearOneDialog(java.awt.Frame parent) {
        super(parent, true);
        w = (WorkShapes) parent;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));
        
        setTitle("Deleting a shape...");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jLabel1.setText("Enter the ID of the shape to clear:");
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        
        getContentPane().add(ID);
        
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        getContentPane().add(jButton1);
        
        pack();
    }//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        w.deleteShape(Integer.valueOf(ID.getText()).intValue());
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField ID;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    
}
