/*
 * PolygonDialog2.java
 *
 * Created on 14. septembre 2001, 11:24
 */

package shapes.gui;

import java.awt.Polygon;

/**
 *
 * @author  fuhrer
 */
public class PolygonDialog2 extends javax.swing.JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3256726195025359417L;
	private Polygon p;
    
    /** Creates new form PolygonDialog2 */
    public PolygonDialog2(java.awt.Dialog parent, Polygon p) {
        super(parent, true);
        this.p = p;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        xcoordlabel = new javax.swing.JLabel();
        xcoord = new javax.swing.JTextField();
        ycoordlabel = new javax.swing.JLabel();
        ycoord = new javax.swing.JTextField();
        
        setTitle("New vertex...");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jLabel1.setText("Adding a vertex");
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);
        
        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });
        
        getContentPane().add(OKButton, java.awt.BorderLayout.SOUTH);
        
        jPanel2.setLayout(new java.awt.GridLayout(2, 2));
        
        xcoordlabel.setText("X coord :");
        jPanel2.add(xcoordlabel);
        
        jPanel2.add(xcoord);
        
        ycoordlabel.setText("Y coord :");
        jPanel2.add(ycoordlabel);
        
        jPanel2.add(ycoord);
        
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // Add your handling code here:
        p.addPoint(Integer.valueOf(xcoord.getText()).intValue(),Integer.valueOf(ycoord.getText()).intValue());
        dispose();
    }//GEN-LAST:event_OKButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
   // public static void main(String args[]) {
   //     new PolygonDialog2(new javax.swing.JFrame(), true).show();
   // }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton OKButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel xcoordlabel;
    private javax.swing.JTextField xcoord;
    private javax.swing.JLabel ycoordlabel;
    private javax.swing.JTextField ycoord;
    // End of variables declaration//GEN-END:variables

}
