/*
 * PolygonDialog.java
 *
 * Created on 14. septembre 2001, 09:35
 */

package shapes.gui;

import shapes.WorkShapes;

/**
 *
 * @author  fuhrer
 */
public class PolygonDialog extends javax.swing.JDialog {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 3977016262398522162L;
	private shapes.Polygon callingShape;
    private WorkShapes w;
    
    private java.awt.Polygon p = new java.awt.Polygon();
    
    /** Creates new form PolygonDialog */
    public PolygonDialog(java.awt.Frame parent) {
        super(parent, true);
        w = (WorkShapes)parent;
        initComponents();
    }
    
    public PolygonDialog(shapes.Polygon p) {
        super();
        setModal(true);
        callingShape = p;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        toppanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        v1xlabel = new javax.swing.JLabel();
        v1x = new javax.swing.JTextField();
        v1ylabel = new javax.swing.JLabel();
        v1y = new javax.swing.JTextField();
        v2xlabel = new javax.swing.JLabel();
        v2x = new javax.swing.JTextField();
        v2ylabel = new javax.swing.JLabel();
        v2y = new javax.swing.JTextField();
        v3xlabel = new javax.swing.JLabel();
        v3x = new javax.swing.JTextField();
        v3ylabel = new javax.swing.JLabel();
        v3y = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        v4x = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        v4y = new javax.swing.JTextField();
        downpanel = new javax.swing.JPanel();
        moreButton = new javax.swing.JToggleButton();
        OKButton = new javax.swing.JButton();
        
        setTitle("Create/Edit a Polygon");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jLabel1.setText("Enter Polygon Data");
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18));
        toppanel.add(jLabel1);
        
        getContentPane().add(toppanel, java.awt.BorderLayout.NORTH);
        
        mainpanel.setLayout(new java.awt.GridLayout(8, 2));
        
        v1xlabel.setText("Vertex 1 X :");
        mainpanel.add(v1xlabel);
        
        mainpanel.add(v1x);
        
        v1ylabel.setText("Vertex 1 Y :");
        mainpanel.add(v1ylabel);
        
        mainpanel.add(v1y);
        
        v2xlabel.setText("Vertex 2 X :");
        mainpanel.add(v2xlabel);
        
        mainpanel.add(v2x);
        
        v2ylabel.setText("Vertex 2 Y :");
        mainpanel.add(v2ylabel);
        
        mainpanel.add(v2y);
        
        v3xlabel.setText("Vertex 3 X :");
        mainpanel.add(v3xlabel);
        
        mainpanel.add(v3x);
        
        v3ylabel.setText("Vertex 3 Y :");
        mainpanel.add(v3ylabel);
        
        mainpanel.add(v3y);
        
        jLabel2.setText("Vertex 4 X :");
        mainpanel.add(jLabel2);
        
        mainpanel.add(v4x);
        
        jLabel3.setText("Vertex 4 Y :");
        mainpanel.add(jLabel3);
        
        mainpanel.add(v4y);
        
        getContentPane().add(mainpanel, java.awt.BorderLayout.CENTER);
        
        moreButton.setText("Define more vertices");
        moreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreButtonActionPerformed(evt);
            }
        });
        
        downpanel.add(moreButton);
        
        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });
        
        downpanel.add(OKButton);
        
        getContentPane().add(downpanel, java.awt.BorderLayout.SOUTH);
        
        pack();
    }//GEN-END:initComponents
    
    private void moreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreButtonActionPerformed
        // Add your handling code here:
        new PolygonDialog2(this,p).setVisible(true);
    }//GEN-LAST:event_moreButtonActionPerformed
    
    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // Add your handling code here:
        p.addPoint(Integer.valueOf(v1x.getText()).intValue(),Integer.valueOf(v1y.getText()).intValue());
        p.addPoint(Integer.valueOf(v2x.getText()).intValue(),Integer.valueOf(v2y.getText()).intValue());
        p.addPoint(Integer.valueOf(v3x.getText()).intValue(),Integer.valueOf(v3y.getText()).intValue());
        p.addPoint(Integer.valueOf(v4x.getText()).intValue(),Integer.valueOf(v4y.getText()).intValue());
        int[] tmpx = new int[p.npoints];
        int[] tmpy = new int[p.npoints];
        for (int i =0; i<p.npoints;i++) {
            tmpx[i]=p.xpoints[i];
            tmpy[i]=p.ypoints[i];
        }
        if (callingShape != null) {
            callingShape.change(tmpx, tmpy);
            setVisible(false);
            dispose();
        } else {
            w.createNewPolygon(tmpx,tmpy);
            setVisible(false);
            dispose();}
    }//GEN-LAST:event_OKButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    //  public static void main(String args[]) {
    //      new PolygonDialog(new javax.swing.JFrame(), true).show();
    //  }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel toppanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JLabel v1xlabel;
    private javax.swing.JTextField v1x;
    private javax.swing.JLabel v1ylabel;
    private javax.swing.JTextField v1y;
    private javax.swing.JLabel v2xlabel;
    private javax.swing.JTextField v2x;
    private javax.swing.JLabel v2ylabel;
    private javax.swing.JTextField v2y;
    private javax.swing.JLabel v3xlabel;
    private javax.swing.JTextField v3x;
    private javax.swing.JLabel v3ylabel;
    private javax.swing.JTextField v3y;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField v4x;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField v4y;
    private javax.swing.JPanel downpanel;
    private javax.swing.JToggleButton moreButton;
    private javax.swing.JButton OKButton;
    // End of variables declaration//GEN-END:variables
    
}
