/*
 * PolygonDialog.java
 *
 * Created on 14. septembre 2001, 09:35
 */

package shapes.gui;

import shapes.WorkShapes;

/**
 *
 * @author  fuhrer
 */
public class TriangleDialog extends javax.swing.JDialog {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 3256442508275037238L;
	private shapes.Polygon callingShape;
    private WorkShapes w;
    
    private java.awt.Polygon p = new java.awt.Polygon();
    
    /** Creates new form PolygonDialog */
    public TriangleDialog(java.awt.Frame parent) {
        super(parent, true);
        w = (WorkShapes)parent;
        initComponents();
    }
    
    public TriangleDialog(shapes.Polygon p) {
        super();
        setModal(true);
        callingShape = p;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        toppanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        v1xlabel = new javax.swing.JLabel();
        v1x = new javax.swing.JTextField();
        v1ylabel = new javax.swing.JLabel();
        v1y = new javax.swing.JTextField();
        v2xlabel = new javax.swing.JLabel();
        v2x = new javax.swing.JTextField();
        v2ylabel = new javax.swing.JLabel();
        v2y = new javax.swing.JTextField();
        v3xlabel = new javax.swing.JLabel();
        v3x = new javax.swing.JTextField();
        v3ylabel = new javax.swing.JLabel();
        v3y = new javax.swing.JTextField();
        downpanel = new javax.swing.JPanel();
        OKButton = new javax.swing.JButton();

        setTitle("Create/Edit a Triangle");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel1.setText("Enter Triangle Data");
        toppanel.add(jLabel1);

        getContentPane().add(toppanel, java.awt.BorderLayout.NORTH);

        mainpanel.setLayout(new java.awt.GridLayout(6, 2));

        v1xlabel.setText("Vertex 1 X :");
        mainpanel.add(v1xlabel);

        v1x.setText("120");
        mainpanel.add(v1x);

        v1ylabel.setText("Vertex 1 Y :");
        mainpanel.add(v1ylabel);

        v1y.setText("120");
        mainpanel.add(v1y);

        v2xlabel.setText("Vertex 2 X :");
        mainpanel.add(v2xlabel);

        v2x.setText("240");
        mainpanel.add(v2x);

        v2ylabel.setText("Vertex 2 Y :");
        mainpanel.add(v2ylabel);

        v2y.setText("200");
        mainpanel.add(v2y);

        v3xlabel.setText("Vertex 3 X :");
        mainpanel.add(v3xlabel);

        v3x.setText("190");
        mainpanel.add(v3x);

        v3ylabel.setText("Vertex 3 Y :");
        mainpanel.add(v3ylabel);

        v3y.setText("350");
        mainpanel.add(v3y);

        getContentPane().add(mainpanel, java.awt.BorderLayout.CENTER);

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        downpanel.add(OKButton);

        getContentPane().add(downpanel, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
        
    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // Add your handling code here:
        p.addPoint(Integer.valueOf(v1x.getText()).intValue(),Integer.valueOf(v1y.getText()).intValue());
        p.addPoint(Integer.valueOf(v2x.getText()).intValue(),Integer.valueOf(v2y.getText()).intValue());
        p.addPoint(Integer.valueOf(v3x.getText()).intValue(),Integer.valueOf(v3y.getText()).intValue());
        int[] tmpx = new int[p.npoints];
        int[] tmpy = new int[p.npoints];
        for (int i =0; i<p.npoints;i++) {
            tmpx[i]=p.xpoints[i];
            tmpy[i]=p.ypoints[i];
        }
        if (callingShape != null) {
            callingShape.change(tmpx, tmpy);
            setVisible(false);
            dispose();
        } else {
            w.createNewTriangle(tmpx,tmpy);
            setVisible(false);
            dispose();}
    }//GEN-LAST:event_OKButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    //  public static void main(String args[]) {
    //      new PolygonDialog(new javax.swing.JFrame(), true).show();
    //  }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField v1y;
    private javax.swing.JTextField v1x;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel downpanel;
    private javax.swing.JLabel v3xlabel;
    private javax.swing.JTextField v2x;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JTextField v3x;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel v2xlabel;
    private javax.swing.JLabel v1xlabel;
    private javax.swing.JLabel v1ylabel;
    private javax.swing.JTextField v2y;
    private javax.swing.JTextField v3y;
    private javax.swing.JLabel v3ylabel;
    private javax.swing.JPanel toppanel;
    private javax.swing.JLabel v2ylabel;
    // End of variables declaration//GEN-END:variables
    
}
