/*
 * WrongFileNameErrorBox.java
 *
 * Created on 13. novembre 2001, 14:22
 */

package shapes.gui;

/**
 *
 * @author  fuhrer
 */
public class WrongFileNameErrorBox extends javax.swing.JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3257286911646315826L;


	/** Creates new form WrongFileNameErrorBox */
    public WrongFileNameErrorBox(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));
        
        setTitle("Error message....");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jLabel1.setText("Error: Wrong Filename !!");
        jLabel1.setToolTipText("Error message...");
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 100));
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 200));
        getContentPane().add(jLabel1);
        
        pack();
    }//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
